#!/usr/bin/env bash


##  simple install script to install config files and scripts


INSTALL_PREFIX=/usr/local



function say()
{
    echo "$@" 1>&2
}


function die()
{
    say "$@"
    exit 1
}


function _help()
{
    cat <<EOF 1>&2

install scripts and config files

options:
--help,-h; display this help message and exit
--dry-run; talk the talk but don't walk the walk
--move-existing; if <file> exists, move it to <file>.old
--verbose; talk the talk AND walk the walk

functionality:
- scripts (in 'scripts' directory) are installed to $INSTALL_PREFIX/bin
  - this invokes sudo, be warned
- configs (in 'dots' directory) are installed to ~/.config/ unless:
  - they are present in '.homedots', in which case they are installed to ~/ 
  - 'dots/sshconfig' is installed to ~/.ssh/config

EOF
}


function install_scripts()
{
    for script in $dname/scripts/*; do
        if (( options_dry_run )); then
            sudo cp $script $INSTALL_PREFIX/bin/
        fi
        if (( options_dry_run || options_verbose )); then
            say "$script -> $INSTALL_PREFIX/bin/"
        fi
    done
}


function install_dots()
{
    for dot in $( find $dname/dots -maxdepth 1 -mindepth 1 -type f,d ); do
        bname="$( basename $dot )"
        if [[ $bname == "sshconfig" ]]; then
			if (( ! options_dry_run )); then
                mkdir -p ~/.ssh
                if [[ -f ~/.ssh/config && ! -L ~/.ssh/config ]]; then
					if (( options_move_existing )); then
						mv ~/.ssh/config ~/.ssh/config.old
						if (( options_verbose )); then
							say "~/.ssh/config -> ~/.ssh/config.old"
						fi
					else
						die "~/.ssh/config exists and is not a symlink, exiting"
					fi
                else
                    rm ~/.ssh/config
                    ln -s $( realpath $dot ) ~/.ssh/config
                fi
            fi
            if (( options_dry_run || options_verbose )); then
                say "$dot -> ~/.ssh/config"
            fi
        elif [[ -n "$( grep $bname < $dname/.homedots )" ]]; then  # install some files to ~/
            if (( options_dry_run )); then
                if [[ -f ~/$bname && ! -L ~/$bname ]]; then
					if (( options_move_existing )); then
						mv ~/$bname ~/$bname.old
						if (( options_verbose )); then
							say "$bname -> $bname.old"
						fi
					else
                    	die "~/$bname exists and is not a symlink, exiting"
					fi
                else
                    rm -rf ~/$bname
                    ln -s $( realpath $dot ) ~/
                fi
            fi
            if (( options_dry_run || options_verbose )); then
                say "$dot -> ~/$bname"
            fi
        else                                  # install remaining files to ~/.config
            if (( options_dry_run )); then
                mkdir -p ~/.config
                if [[ -f ~/.config/$bname && ! -L ~/.config/$bname ]]; then
					if (( options_move_existing )); then
						mv ~/.config/$bname ~/.config/$bname.old
						if (( options_verbose )); then
							say ".config/$bname -> .config/$bname.old"
						fi
					else
                    	die "~/.config/$bname exists and is not a symlink, exiting"
					fi
                else
                    rm -rf ~/.config/$bname
                    ln -s $( realpath $dot ) ~/.config/
                fi
            fi
            if (( options_dry_run || options_verbose )); then
                say "$dot -> ~/.config/$bname"
            fi
        fi
    done
}


dname="$( dirname $0 )"

for arg in "$@"; do
    if [[ $arg == "--help" || $arg == "-h" ]]; then
        _help
        exit 0
    elif [[ $arg == "--dry-run" ]]; then
        options_dry_run=1
    elif [[ $arg == "--verbose" ]]; then
        options_verbose=1
    elif [[ $arg == "--move-existing" ]]; then
        options_move_existing=1
    fi
done


install_scripts
install_dots
