#!/usr/bin/env bash


# Start a new tmux session with regular dev dependencies


set -o errexit
set -o xtrace


# Get tmux session name as positional arg
session_name="$1"
[[ -n "$session_name" ]] || { echo "tmux session name required as argument" >&2; exit 1; }

# We will source the relevant venv in every window, so we must determine which is the
# relevant venv, starting with the active venv (if there is one), falling back on the HQ
# default. We construct a command string to source the venv for later convenience
venv_path="$VIRTUAL_ENV"
[[ -n "$venv_path" ]] || venv_path="$HQ_VENV"
[[ -n "$venv_path" ]] || { echo "Could not determine virtual env path from active venv or " >&2; exit 1; }
SOURCE_VENV="source \"$venv_path/bin/activate\""

# Before we go launching emacs, display a warning if there is already an emacs server
# running (in an unknown environment)
ps aux | grep -v "grep" | grep "emacs --daemon" >/dev/null &&
    echo "WARNING: emacs server is already running, so may not be in venv: $venv_path">&2

# Start tmux server
tmux start

# Create a new tmux session, with our first window, "edit", used for emacs
tmux new-session \
     -ds "$session_name" \
     -n edit \
     -c "$HOME/src/abyss" \
     "$SOURCE_VENV && em"

# Make a new window for claude
tmux new-window -a \
     -t "$session_name:edit" \
     -n claude \
     -c "$HOME/src/abyss" \
     "$SOURCE_VENV && sleep 2 && claude --ide"

# Make a "repl" window with an ipython interpreter
tmux new-window -a \
     -t "$session_name:claude" \
     -n repl \
     "$SOURCE_VENV && ipython"

# Make a new window for each of the holy trinity repos
tmux new-window -a \
     -t "$session_name:claude" \
     -n bedrock \
     -c "$HOME/src/abyss/abyss-bedrock"
tmux new-window -a \
     -t "$session_name:bedrock" \
     -n deepl \
     -c "$HOME/src/abyss/deep-learning"
tmux new-window -a \
     -t "$session_name:deepl" \
     -n fabric \
     -c "$HOME/src/abyss/abyss-fabric"

# Attach to the session
tmux attach -t "$session_name"
