#!/usr/bin/env bash


##  bash-std
#
# A collection of handy functions that can be sourced in one line:
#             source $( type -p bash-std )
# 
# Note: It is easiest to test any changes made to bash-std on sysbs, as it
#       sources the bash-std in hq, not the system installed one



function say
{
    echo -e "${fmt_bold}$( basename $0 )${fmt_reset}: $@" 1>&2
}

function saymore
{
    if (( options_verbose )); then
        say "$@"
    fi
}

function die
{
    say "${fmt_red}$@${fmt_reset}"
    exit 1
}

function timestamp
{
    date --iso-8601=seconds | sed -e 's#+.*##' -e 's#[-:]##g'
}

function bash-std-set-verbose
{
    if (( options_verbose )); then
         verbose="v"
        _verbose="-v"
    else
         verbose=""
        _verbose=""
    fi
}

export -f say
export -f saymore
export -f die
export -f bash-std-set-verbose




fmt_reset="$(tput sgr0)"
fmt_bold="$(tput bold)"
fmt_dim="$(tput dim)"
fmt_underline_enable="$(tput smul)"
fmt_underline_disable="$(tput rmul)"
fmt_black="$(tput setaf 0)"
fmt_red="$(tput setaf 1)"
fmt_green="$(tput setaf 2)"
fmt_yellow="$(tput setaf 3)"
fmt_blue="$(tput setaf 4)"
fmt_magenta="$(tput setaf 5)"
fmt_cyan="$(tput setaf 6)"
fmt_white="$(tput setaf 7)"

export fmt_reset
export fmt_bold
export fmt_dim
export fmt_underline_enable
export fmt_underline_disable
export fmt_black
export fmt_red
export fmt_green
export fmt_yellow
export fmt_blue
export fmt_magenta
export fmt_cyan
export fmt_white


command -v notify-send > /dev/null && BASH_STD_NOTIFY_SEND_INSTALLED=1
export BASH_STD_NOTIFY_SEND_INSTALLED


# @@@ BASH-STD VERSIONING @@@
BASH_STD_VERSION="2.0.0"

# Compare two version strings. Returns 0 if $1 >= $2.
function _bash_std_version_ge {
    [[ "$1" == "$2" ]] && return 0
    local IFS=.

    # Coerce version strings into arrays, filling missing parts with zeros
    local i ver1=($1) ver2=($2)
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
        ver1[i]=0
    done

    # Check each version number segment
    for ((i=0; i<${#ver1[@]}; i++)); do
        if [[ -z ${ver2[i]} ]]; then
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]})); then
            return 0
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]})); then
            return 1
        fi
    done
    return 0
}

# Automatically update bash-std if it is older than $BASH_STD_MIN_VERSION
function _bash_std_check_version {
    if [[ -n "$BASH_STD_MIN_VERSION" ]]; then
        if ! _bash_std_version_ge "$BASH_STD_VERSION" "$BASH_STD_MIN_VERSION"; then
            local bash_std_path="${BASH_SOURCE[0]:-$0}"

            # If we're sourced and not writable, we can't update ourselves.
            if [[ ! -w "$bash_std_path" ]]; then
                die "bash-std is too old (v$BASH_STD_VERSION < v$BASH_STD_MIN_VERSION) and cannot update itself because $bash_std_path is not writable. Please update bash-std manually or modify permissions with chmod +w $bash_std_path."
            fi

            # Avoid recursive updates if something goes wrong
            if [[ "$BASH_STD_UPDATING" == "1" ]]; then
                return
            fi
            export BASH_STD_UPDATING=1

            say "bash-std is too old (v$BASH_STD_VERSION < v$BASH_STD_MIN_VERSION), updating from GitHub..."
            local temp_file=$(mktemp)
            if curl -fsSL https://raw.githubusercontent.com/hacmorgan/hq/refs/heads/main/applications/bash-std -o "$temp_file"; then
                # Check the version of the downloaded file
                local new_version=$(sed -n "s/BASH_STD_VERSION=\x22\([^\x22]*\)\x22/\1/p" "$temp_file" | head -n 1)
                if [[ -n "$new_version" ]] && _bash_std_version_ge "$new_version" "$BASH_STD_MIN_VERSION"; then
                    mv "$temp_file" "$bash_std_path"
                    chmod +x "$bash_std_path"
                    unset BASH_STD_UPDATING
                    source "$bash_std_path"
                    return 1
                fi
            fi
            rm -f "$temp_file"
            unset BASH_STD_UPDATING
        fi
    fi
}

_bash_std_check_version || return 0
# @@@ END BASH-STD VERSIONING @@@


function get_definition
{
    arg="$1"
    grep --regexp "^$arg\*\?;" \
         --regexp "^$arg\*\?," \
         --regexp "^$arg\*\?=" \
         --regexp ",$arg\*\?;" \
         --regexp ",$arg\*\?," \
         --regexp ",$arg\*\?="
}

function full_arg_name
{
    sed --expression 's#;.*##' \
        --expression 's#=.*##' \
        --expression 's#,.*##' \
        --expression 's#\*##g'
}

function argument_type
{
    local options=$( cat )
    local arg_name="$( cut -d'=' -f1 <<< $1 )"
    local definition="$( get_definition "$arg_name" <<< $options )"
    if [[ -n "$( grep '=<.*>;'     <<< $definition )" || \
          -n "$( grep '=\[<.*>\];' <<< $definition )" ]]; then
        if [[ -n "$( grep '=' <<< "$1" )" ]]; then
            echo "comes_with_value"
        else
            echo "value_in_next_arg"
        fi
    elif [[ -z "$definition" ]]; then
        echo "not_an_option"
    elif [[ "$definition" != -* ]]; then
        echo "positional"
    else
        echo "flag"
    fi
}

function arg_to_option_name
{
    local options=$( cat )
    local argument="$1"
    local definition="$( get_definition "$argument" <<< $options )"
    local full_name="$( full_arg_name <<< $definition )"
    sed --expression 's#^#options_#' \
        --expression 's#--##'        \
        --expression 's#-#_#g'       \
        <<< "$full_name"
}

function set_value
{
    local options=$( cat )
    expression="$( arg_to_option_name "$1" <<< $options )=$2"
    eval "$expression"
}

function set_defaults
{
    local definition=""
    while read definition; do
        local arg_name=$( full_arg_name           <<< $definition )
        local arg_type=$( argument_type $arg_name <<< $definition )
        if [[ $arg_type == "flag" ]]; then
            set_value $arg_name 0 <<< $definition
        elif [[ $arg_type == "positional" && "$definition" == *'*'* ]]; then
            local varname=$( arg_to_option_name "$arg_name" <<< $definition )
            eval "${varname}=()"
        else
            local value=""
            if [[ -n "$( grep 'default=' <<< $definition )" ]]; then
                value="$( sed -e 's#.*default=##' -e 's#;.*##' <<< $definition )"
            fi
            set_value $arg_name $value <<< $definition
        fi
    done
}

function check_all_mandatory_options
{
    local definition=""
    while read definition; do
        local arg_name=$( full_arg_name           <<< $definition )
        local arg_type=$( argument_type $arg_name <<< $definition )
        if [[ -n "$( grep "value" <<< $arg_type )" && -z "$( grep "\[<.*>\]" <<< $definition )" ]] ||
           [[ $arg_type == "positional" && "$definition" != *'*'* && -z "$( grep 'default=' <<< $definition )" ]]; then
            variable_name="$( arg_to_option_name "$arg_name" <<< $definition )"
            [[ -n $( eval "echo \$$variable_name" ) ]] || die "$arg_name is required and was not given"
        fi
    done
}

function check_for_help
{
    local args=( $@ )
    local _help=0
    for arg in ${args[@]}; do
        if [[ $arg == "-h" || $arg == "--help" ]]; then
            _help=1
            break
        fi
    done
    if (( _help )); then
        command -v prologue > /dev/null && { prologue; echo; }
        echo "${fmt_bold}options:${fmt_reset}"
        cat | sed -e 's#^#    #' \
                  -e "s#\(.*\);\(.*\)#\1;${fmt_dim}\2${fmt_reset}#" \
                  1>&2
        command -v epilogue > /dev/null && epilogue
        exit 0
    else
        cat 1>/dev/null
    fi
}

function bash-std-application-init
{
    function check_if_expecting_value
    {
        if (( this_is_value )); then
            die "Was expecting ${args[$i]} to be a value for the argument ${args[$(( i - 1 ))]}"
        fi
    }

    local options=$( cat )
    args=( "$@" )
    nargs=$(( ${#args[@]} - 1 ))

    check_for_help ${args[@]} <<< $options
    set_defaults              <<< $options

    # Collect positional argument names in definition order (lines without a leading -)
    # Names ending in * are variadic: they collect all remaining positional args into an array
    local positional_defs=()
    local positional_is_variadic=()
    while IFS= read -r _def; do
        local _name
        _name=$(sed -e 's/;.*//' -e 's/=.*//' -e 's/,.*//' -e 's/\*//' -e 's/[[:space:]]//g' <<< "$_def")
        positional_defs+=("$_name")
        if [[ "$_def" == *'*'* ]]; then
            positional_is_variadic+=(1)
        else
            positional_is_variadic+=(0)
        fi
    done < <(grep --invert-match --regexp '^-' --regexp '^[[:space:]]*$' <<< "$options")
    local positional_index=0

    next_is_value=0
    this_is_value=0
    for i in $( seq 0 $nargs ); do  # for some reason {0..${#args[@]}} didn't work
        if (( next_is_value )); then
            next_is_value=0
            this_is_value=1
        fi
        local arg_type=$( argument_type "${args[$i]}" <<< $options )
        case $arg_type in
            "comes_with_value")
                check_if_expecting_value
                set_value "$( cut -d'=' -f1              <<< ${args[$i]} )" \
                          "$( cut -d'=' -f1 --complement <<< ${args[$i]} )" \
                          <<< $options ;;
            "value_in_next_arg")
                check_if_expecting_value
                next_is_value=1
                set_value "${args[$i]}"           \
                          "${args[$(( i + 1 ))]}" \
                          <<< $options ;;
            "flag")
                check_if_expecting_value
                set_value "${args[$i]}" 1 <<< $options ;;
            "not_an_option")
                if (( this_is_value )); then
                    this_is_value=0
                    continue
                fi
                if (( positional_index < ${#positional_defs[@]} )); then
                    if (( positional_is_variadic[positional_index] )); then
                        local _varname
                        _varname=$( arg_to_option_name "${positional_defs[$positional_index]}" <<< $options )
                        eval "${_varname}+=( $(printf '%q' "${args[$i]}") )"
                    else
                        set_value "${positional_defs[$positional_index]}" \
                                  "${args[$i]}" \
                                  <<< $options
                        (( positional_index++ ))
                    fi
                elif (( ! BASH_STD_IGNORE_UNKNOWN_ARGS )); then
                    die "unrecognised argument: ${args[$i]}"
                fi ;;
        esac
    done

    check_all_mandatory_options <<< $options
}

export -f bash-std-application-init




function whats-my-private-ip
{
    ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}'
}

export -f whats-my-private-ip
