#!/usr/bin/env bash

# A simple script to open a given file in emacs,
# and detatch the process from the parent terminal

source $(type -p bash-std)

function prologue {
    cat <<EOF

${fmt_red}em - emacsclient wrapper${fmt_reset}
EOF
}

function options {
    cat <<EOF
files*; Input files to open in emacs
--detach,-d; Open file in emacs server but don't launch an emacs window
--sudo,-s; Open file using sudo
--gui,-x; Open file in GUI instead of terminal
EOF
}

bash-std-application-init "$@" < <(options) || die "failed"

function sanitize_inputs {
    if ((options_detach + options_gui > 1)); then
        die "--detach and --gui are mutually exclusive"
    fi
}

# Check args are legit
sanitize_inputs

# Construct the common start of the command
command="emacsclient -a ''"

# Add appropriate prefix depending if we're opening here or somewhere else
if ((options_detach)); then
    command+=" -n"
else
    command+=" -c"
fi

# Add the filepath(s)
for _file in "${options_files[@]}"; do
    if ((options_sudo)); then
        command+=" /sudo::$(realpath "$_file")"
    else
        command+=" $_file"
    fi
done

# Set args for GUI/TUI
if ((options_gui)); then
    command+=" &!"
else
    command+=" -nw"
fi

# Run emacs
eval "$command"
