#!/usr/bin/env python3


"""
Lightweight application for writing and aggregating TODOs
"""


from hq.cli.todo import todo

from hq.cli import run_typer_app


if __name__ == "__main__":
    run_typer_app(todo)
