#!/usr/bin/env bash


source $( type -p bash-std )


function prologue
{
    cat <<EOF 
EOF
}

function options
{
    cat <<EOF
EOF
}

function epilogue
{
    cat <<EOF
EOF
}


bash-std-application-init "$@" < <( options ) || die "failed"

# command line args are now defined
