#!/usr/bin/env python3


import argparse
import sys


def getArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument("verbose", "v", action="store_true", help="more output")
    return parser.parse_args()


def main(args):
    return 0


if __name__ == '__main__':
    sys.exit(main(getArgs()))
