#!/usr/bin/env bash


##  dmenu-custom - collection of convenient shell commands and routines
#
# Intended to be bound to a key combination in a wondow manager
#
# Author:  Hamish Morgan
# Date:    02/05/2021
# License: BSD


source $(type -p bash-std)


function get_choice()
{
    options="$1"
    echo $options                       |
        tr ',' '\n'                     |
        dmenu -fn "Fantasque Sans Mono" \
              -sb "#AD29C4"             \
              -f
}


function main-run ()
{
    function power-run()
    {
        local options="shut down,reboot"
        local selected_option="$(get_choice "$options")"
        case "$selected_option" in
            "shut down")
                sudo shutdown -P now ;;
            "reboot")
                sudo reboot ;;
        esac
    }
    
    function edit-configs-run ()
    {
        local configs="zsh,i3,i3status,emacs,picom,kitty,xinit,dmenu-custom"
        local selected_config="$(get_choice "$configs")"
        case "$selected_config" in
            "zsh")
                em ~/.zshrc ;;
            "i3")
                em ~/.config/i3/config ;;
            "i3status")
                em ~/.config/i3/status.toml ;;
            "dwm")
                em ~/src/foss/dwm/config.h ;;
            "emacs")
                em ~/.emacs.d/config.org ;;
            "picom")
                em ~/.config/picom.conf ;;
            "kitty")
                em ~/.config/kitty/kitty.conf ;;
            "sakura")
                em ~/.config/sakura/sakura.conf ;;
            "termite")
                em ~/.config/termite/config ;;
            "st")
                em ~/src/foss/st/config.h ;;
            "xinit")
                em ~/.xinitrc ;;
            "dmenu-custom")
                em ~/src/hq/scripts/dmenu-custom ;;
        esac
    }

    function screenshot-run()
    {
        local screenshot_types="select region,full screen,select region (delay),full screen (delay)"
        local selected_type="$(get_choice "$screenshot_types")"
        local expression='mv $f /tmp/'
        if (( BASH_STD_NOTIFY_SEND_INSTALLED )); then
            expression+='; notify-send "screenshot captured" "saved to $f"'
        fi
        case "$selected_type" in
            "select region")
                scrot -s -e "$expression" ;;
            "full screen")
                scrot -e "$expression" ;;
        esac
    }

    # TODO - determine appropriate values
    function keyboard-multiplier-run()
    {
        function select-delay()
        {
            local delays="150ms,250ms,500ms"
            local selected_delay="$(get_choice "$delays" | sed 's/ms//g')"
            local current_rate=$(xset -q | grep delay | cut -d: -f3 | cut -d ' ' -f3)
            xset r rate $selected_delay $current_rate
        }
        function select-rate()
        {
            local rates="25,50,100,200"
            local selected_rate="$(get_choice "$rates")"
            local current_delay=$(xset -q | grep delay | cut -d: -f2 | cut -d ' ' -f3)
            xset r rate $current_delay $selected_rate
        }
        
        local configurable_params="delay,rate"
        local selected_param="$(get_choice "$configurable_params")"
        case "$selected_param" in
            "delay")
                select-delay ;;
            "rate")
                select-rate ;;
        esac
    }

    function mouse-speed-run()
    {
        function select-acceleration()
        {
            local delays="150ms,250ms,500ms"
            local selected_delay="$(get_choice "$delays" | sed 's/ms//g')"
            local current_rate=$(xset -q | grep delay | cut -d: -f3 | cut -d ' ' -f3)
            xset r rate $selected_delay $current_rate
        }
        function select-threshold()
        {
            local rates="25,50,100,200"
            local selected_rate="$(get_choice "$rates")"
            local current_delay=$(xset -q | grep delay | cut -d: -f2 | cut -d ' ' -f3)
            xset r rate $current_delay $selected_rate
        }
        
        local configurable_params="acceleration,threshold,restore defaults"
        local selected_param="$(get_choice "$configurable_params")"
        case "$selected_param" in
            "acceleration")
                select-acceleration ;;
            "threshold")
                select-threshold ;;
            "restore defaults")
                xset m default
        esac
    }

    function picom-run()
    {
        local picom_options="turn on,turn off"
        local selected_option="$(get_choice "$picom_options")"
        case "$selected_option" in
            "turn on")
                [ $(ps -aux | grep picom | wc -l) -le 1 ] && exec picom
                if (( BASH_STD_NOTIFY_SEND_INSTALLED )); then
                    notify-send "picom turned on"
                fi ;;
            "turn off")
                killall picom
                if (( BASH_STD_NOTIFY_SEND_INSTALLED )); then
                    notify-send "picom turned off"
                fi ;;
        esac
    }

    function emacs-run
    {
        function is_remote
        {
            local options="local,remote"
            local selected_option="$(get_choice "$options")"
            case "$selected_option" in
                "local")
                    echo 0 ;;
                "remote")
                    echo 1 ;;
            esac
        }
        
        local emacs_options="local,george,buffalo"
        local selected_option="$(get_choice "$emacs_options")"
        case "$selected_option" in
            "local")
                em ;;
            "george")
                em --george ;;
            "buffalo")
                if (( $(is_remote) )); then
                    em --buffalo --via-george
                else
                    em --buffalo
                fi ;;
            "enzo")
                if (( $(is_remote) )); then
                    em --enzo --via-george
                else
                    em --enzo
                fi ;;
        esac
    }

    function display-run
    {
        local display_options="turn off,all monitors,flat only,wide only,curved only,flat and wide"
        local selected_option="$(get_choice "$display_options")"
        case "$selected_option" in
            "turn off")
                xset -display :0.0 dpms force off ;;
            "all monitors")
                use-all-monitors ;;
            "flat only")
                use-flat-only ;;
            "wide only")
                use-wide-only ;;
            "curved only")
                use-curved-only ;;
            "flat and wide")
                use-flat-and-wide ;;
        esac
    }

    function sdc-run
    {
        local options="all,bedside light,whiteboard light,sound system"
        local selected_option="$(get_choice "$options")"
        local states="on,off"
        local selected_state="$(get_choice "$states")"
        case "$selected_state" in
            "on")
                sdc --notify --on "$selected_option" ;;
            "off")
                sdc --notify --off "$selected_option" ;;
        esac
    }

    function bedtime-run
    {
        george-display-off-run
        ssh -J "$(where-is-george)" enzo sudo shutdown now
        sdc --off "all"
    }

    function george-display-off-run
    {
        ssh "$(where-is-george)" xset -display :0.0 dpms force off
    }

    function rotate-speakers-run
    {
        function speaker_angle
        {
            local desired="$1"
            local actual="$2"
            local angle="$3"
            if [[ "$desired" == "both" || "$desired" == "$actual" ]]; then
                echo "$angle"
            else
                echo 0
            fi
        }

        function strip_shortcut_keys
        {
            # Remove embelishments from dmenu hotkeys
            # i.e. "a [-90]" -> "-90"
            sed 's#[a-zA-Z ]*\[\([0-9-]*\)\]#\1#g'
        }
        
        local speakers="both,left,right"
        local angles="a [-90],s [-45],d [-15],f [-5],g [-1],h [1],j [5],k [15],l [45],; -> 90"
        speaker="$(get_choice "$speakers")"
        angle="$(get_choice "$angles" | strip_shortcut_keys)"
        left="$(speaker_angle "$speaker" left "$angle")"
        right="$(speaker_angle "$speaker" right "$angle")"
        echo "rotating speaker $speaker by angle $angle (degrees $left,$right)" 1>&2
        rotate-speakers --degrees="$left,$right"
    }

    
    subsetting_options="power,screenshot,emacs,display,sdc,mount shared drives,rotate speakers,edit configs,keyboard multiplier,picom,bedtime,george display off"
    subsetting="$(get_choice "$subsetting_options")"
    echo $subsetting
    case "$subsetting" in
        "power")
            power-run ;;
        "edit configs")
            edit-configs-run ;;
        "keyboard multiplier")
            keyboard-multiplier-run ;;
        "screenshot")
            screenshot-run ;;
        "picom")
            picom-run ;;
        "emacs")
            emacs-run ;;
        "display")
            display-run ;;
        "mount shared drives")
            mount-shared-drives --notify ;;
        "sdc")
            sdc-run ;;
        "bedtime")
            bedtime-run ;;
        "george display off")
            george-display-off-run ;;
        "rotate speakers")
            rotate-speakers-run ;;
    esac
}


main-run
