#!/usr/bin/env bash


# Return JSON formatted string for i3status-rust to use as battery indicator


BATTERY_STATUS_FILE=/tmp/.battery_level


text="Bat: "
if [[ ! -e "$BATTERY_STATUS_FILE" ]]; then
    text+="???"
    state="Idle"
    icon="bat_not_available"
else
    text+="$(cat "$BATTERY_STATUS_FILE")"
    batteryLevelInt="$(cut -d. -f1 < "$BATTERY_STATUS_FILE")"
    if (( batteryLevelInt > 50 )); then
        state="Good"
        icon="bat_discharging"
    elif (( batteryLevelInt > 30 )); then
        state="Info"
        icon="bat_half"
    elif (( batteryLevelInt > 15 )); then
        state="Warning"
        icon="bat_quarter"
    else
        state="Critical"
        icon="bat_empty"
    fi
fi

cat <<EOF
{ 
  "icon"  : "$icon",
  "state" : "$state",
  "text"  : "$text"
}
EOF
