#!/bin/sh
xrandr --output HDMI-0  --off                                                                 \
       --output DP-0    --off                                                                 \
       --output DP-1    --off                                                                 \
       --output DP-2    --off                                                                 \
       --output DP-3    --off                                                                 \
       --output DP-4    --mode 1920x1080 --pos 201x0 --rotate normal  --rate 144.00           \
       --output DP-5    --off
