#!/bin/sh
xrandr --output DVI-I-0 --off                                                                 \
       --output DVI-I-1 --off                                                                 \
       --output HDMI-0  --mode 1920x1080 --pos 2121x0 --rotate normal                         \
       --output DP-0    --mode 1920x1080 --pos 201x0 --rotate normal                          \
       --output DP-1    --off                                                                 \
       --output DP-2    --primary --mode 3840x1080 --pos 0x1080 --rotate normal               \
       --output DP-3    --off                                                                 \
       --output DP-4    --off                                                                 \
       --output DP-5    --off
       # --output DP-0    --mode 1920x1080 --pos 201x0 --rotate normal --rate 144.00            \
       # --output DP-2    --primary --mode 3840x1080 --pos 0x1080 --rotate normal --rate 120.02 \
