#!/bin/sh
xrandr --output DVI-I-0 --off                                                                 \
       --output DVI-I-1 --off                                                                 \
       --output HDMI-0  --off                                                                 \
       --output DP-0    --off                                                                 \
       --output DP-1    --off                                                                 \
       --output DP-2    --primary --mode 3840x1080 --pos 0x1080 --rotate normal --rate 120.02 \
       --output DP-3    --off                                                                 \
       --output DP-4    --off                                                                 \
       --output DP-5    --off
