#!/usr/bin/env bash


source $( type -p bash-std )


function shouldCheckLocal
{
	[[ $( whats-my-private-ip | cut -d'.' -f'1-2' ) == "10.0" ]]
}

hosts=()
if $( shouldCheckLocal ); then
    hosts+=( george )
fi
hosts+=( george_remote )

for host in ${hosts[@]}; do
    ssh $host "exit" 2> /dev/null
    if (( $? == 0 )); then
        echo $host
        exit 0
    fi
done
die "could not reach george or george_remote"
