#!/usr/bin/env python3


import argparse
import sys
import ytmusicapi


def getArgs() -> argparse.Namespace:
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("--auth-header-file",
                        type=str,
                        default="/home/hamish/src/hq/etc/ytmusic_headers_auth.json",
                        help="File to use for authentication, write to this file with --setup\n(default %(default)s)")
    parser.add_argument("--setup", "-s", action="store_true", help="Perform initial authentication")
    parser.add_argument("--verbose", "-v", action="store_true", help="More output")
    return parser.parse_args()


def setup(authHeaderFile: str) -> int:
    print("Generating authentication headers file...\n"
          "see https://ytmusicapi.readthedocs.io/en/latest/setup.html", file=sys.stderr)
    ytmusicapi.YTMusic.setup(filepath=authHeaderFile)
    return 0


def 


def main(args) -> int:
    if args.setup:
        return setup(args.auth_header_file)
    
    

if __name__ == '__main__':
    sys.exit(main(getArgs()))
