#!/bin/sh
xrandr --output HDMI-0  --off                                                                 \
       --output DP-0    --mode 3840x1080 --pos 0x1080 --rotate normal --rate 143.81 --primary \
       --output DP-1    --off                                                                 \
       --output DP-2    --off                                                                 \
       --output DP-3    --off                                                                 \
       --output DP-4    --off                                                                 \
       --output DP-5    --off
