#!/usr/bin/env bash


##  where-is-george - find 


source "$(type -p bash-std)"


function should_check_local
{
	[[ $( whats-my-private-ip | cut -d'.' -f'1-2' ) == "192.168" ]]
}


hosts=()
if should_check_local; then
    hosts+=( george )
fi
hosts+=( george_remote )

for host in "${hosts[@]}"; do
    if ssh "$host" "exit" 2>/dev/null; then
        echo "$host"
        exit 0
    fi
done

die "could not reach george or george_remote"
